FROM golang:1.21-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN apk add --no-cache git
RUN go mod download
COPY . .
RUN go build -o /joevis-backend

FROM alpine:3.18
COPY --from=build /joevis-backend /joevis-backend
WORKDIR /
EXPOSE 8080
ENV ADMIN_PASSWORD=adminpass
CMD ["/joevis-backend"]